classdef animalList
    
    properties
        % edit here for a list of experimental animals that will populate
        % the menu on the GUI
        mouseList = {'mouse1';  ...
                     'mouse2';  ...
                     'mouse3';  ...
                     };
        
    end
    
    % these are experimental parameters, each mouse in the list above shold
    % have 
    properties (Constant)
        
        % inactivation grids to be loaded in association with each mouse
        gridList  = {'fullGridBilateral.mat';               ...
                     'fullGridBilateral.mat';               ...
                     'fullGridBilateral.mat';               ...
                     };
        
        % laser power           
        powerList = {1.5; ...
                     1.5; ...
                     1.5; ...
                     };
        
        % special case to run different powers within a session          
        varPower  = [false;     ...
                     false;     ...
                     false;     ...
                     ];
        
        % trial epoch in which to turn the laser on           
        epochList = {'whole';   ...
                     'cue';     ...
                     'whole';   ...
                     };
        
        % whether to actually run the laser experiments or not. this is intended
        % as an experiment scheduling aid, will not automatically  override any laser
        % functions 
        runOnLsr  = [true;     ...
                     true;     ...
                     false;    ...
                     ];

    end
    
    methods
        
        function obj = addToList(obj,mouse)
            obj.mouseList{end+1} = mouse{1};
            obj.mouseList{end+1} = 'add new';
        end
    end
end